#!/bin/bash

# Beaker installation and extension
beakerx install
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build 
jupyter labextension install beakerx-jupyterlab --no-build 

# Git Jupyter/Lab extension 
jupyter labextension install @jupyterlab/git --no-build 
jupyter serverextension enable --py jupyterlab_git

# Github Jupyter Lab extension
jupyter labextension install @jupyterlab/github --no-build 

# Draw.io Jupyter Lab extension
jupyter labextension install jupyterlab-drawio --no-build 

# Rise Jupyter extension (presentation mode)
jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable  rise --py --sys-prefix

# Plotly Jupyter Lab extension
jupyter labextension install @jupyterlab/plotly-extension --no-build 

# Table of contents Jupyter Lab Extension
jupyter labextension install @jupyterlab/toc --no-build 

# Building everything
jupyter lab build --dev




