#!/bin/bash

# # Beaker installation and extension
 beakerx install
 jupyter labextension install @jupyter-widgets/jupyterlab-manager
 jupyter labextension install beakerx-jupyterlab

# # Git Jupyter/Lab extension 
 jupyter labextension install @jupyterlab/git
 jupyter serverextension enable --py jupyterlab_git

# # Jupyter/Lab extension for iframe/url https://github.com/timkpaine/jupyterlab_iframe
jupyter labextension install jupyterlab_iframe
jupyter serverextension enable --py jupyterlab_iframe

# # Github Jupyter Lab extension
 jupyter labextension install @jupyterlab/github

# # Draw.io Jupyter Lab extension
 jupyter labextension install jupyterlab-drawio

# # Rise Jupyter extension (presentation mode)
 jupyter-nbextension install rise --py --sys-prefix
 jupyter-nbextension enable  rise --py --sys-prefix

# # Plotly Jupyter Lab extension
 jupyter labextension install @jupyterlab/plotly-extension

# # Table of contents Jupyter Lab Extension
 jupyter labextension install @jupyterlab/toc

# # A spell checker extension for markdown cells in jupyterlab notebooks. https://github.com/ijmbarr/jupyterlab_spellchecker
# jupyter labextension install @ijmbarr/jupyterlab_spellchecker

# # JupyterLab extension mimerenderer to render HTML files in IFrame Tab. https://github.com/mflevine/jupyterlab_html
# jupyter labextension install @mflevine/jupyterlab_html

# # Building everything
 jupyter lab build --dev




